---
title: "p8105_hw2_brm2150"
author: "Brooklynn McNeil"
date: "2024-09-24"
output: html_document
---
This is an R markdown document for the homework assignment #2 for the p8105 Data Science 1 Class.

Load Packages

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(readxl)
```

## Problem 1


## Problem 2

Load Trash Wheel Data from excel.

```{r}
mr.trashwheel_df = 
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N586", na = "") |>
  janitor::clean_names() |>
  mutate(sports_balls = round(sports_balls)) |>
  mutate(sports_balls = as.integer(sports_balls)) |>
  mutate(year = as.double(year)) |>
  mutate(trash_wheel = "mr")

mr.trashwheel_df

prof.trashwheel_df =  
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M108", na = "") |>
  janitor::clean_names() |>
  mutate(trash_wheel = "prof") 

prof.trashwheel_df

gwyn.trashwheel_df = 
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", sheet = "Gwynnda Trash Wheel", range = "A2:L157", na = "") |>
  janitor::clean_names() |>
  mutate(trash_wheel = "gwyn") 

gwyn.trashwheel_df

trashwheel_df = 
  bind_rows(mr.trashwheel_df,prof.trashwheel_df, gwyn.trashwheel_df)

trashwheel_df
```

## Problem 3


